<?xml version="1.0"?>
<package format="3">
  <name>robot_bringup</name>
  <version>0.0.0</version>
  <description>Launch and configuration entry point for robot VLN experiments.</description>
  <maintainer email="mifcom2@example.com">mifcom2</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>b2_control</exec_depend>
  <exec_depend>b2_platform</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>dummy_adapter</exec_depend>
  <exec_depend>dualvln_adapter</exec_depend>
  <exec_depend>ticvla_adapter</exec_depend>
  <exec_depend>navila_adapter</exec_depend>
  <exec_depend>uninavid_adapter</exec_depend>
  <exec_depend>omnivla_adapter</exec_depend>
  <exec_depend>dynanav_bridge</exec_depend>
  <exec_depend>navigation_bridge</exec_depend>
  <exec_depend>robot_controller</exec_depend>
  <exec_depend>vln_evaluation</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
