name: unitree_b2w
urdf: ../urdf/b2w_description.urdf
mesh_directory: ../meshes
source:
  repository: third_party/robot_lab
  commit: dda1510
  path: source/robot_lab/data/Robots/unitree/b2w_description
