experiment: b2w_hospital
robot_config: configs/robot.yaml
sensor_config: configs/sensors.yaml
interface_config: src/vln_interface/config/interface.yaml
navigation_bridge_config: src/navigation_bridge/config/bridge.yaml
scene: hospital
controller_mode: goal
vln_model: null
