robot: unitree_b2w
controller_config: src/robot_controller/config/b2w.yaml
description_config: src/robot_description/config/b2w.yaml
command_interface: [vx, vy, yaw_rate]
velocity_topic: /nav_vel
ros_velocity_bridge: pending
